name: Solace Onboarding
description: This is form is for Product Teams to request for onboarding of their application to Solace event broker
title: "[New App]: "
labels: ["new"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Please fill the form
  - type: input
    id: productTeam
    attributes:
      label: Product Team
    validations:
      required: true
  - type: input
    id: application
    attributes:
      label: Application Name
    validations:
      required: true
  - type: input
    id: queue
    attributes:
      label: Queue Name
    validations:
      required: false
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Deploy to environment
      options:
        - Development
        - PreProduction
        - Production
    validations:
      required: true
